### ISSUE TITLE
tags removal

### ISSUE THREAD

**Issue by wsor4035** [bobmitch/SeamlessCMS#118]
when tags are removed from media items on the backend, they are not graphically removed till the page is refreshed

**Comment by bobmitch** [comment]
Fixed in https://github.com/bobmitch/SeamlessCMS/commit/335410f0dc0c84398b72fc08ca09e0da3ef98d7d

Please test and close.

**Comment by bobmitch** [comment]
Or rather, pull change into the TAH site and test, I only changed in the upstream repo.
